[package]
name = "chromaprint"
version = "0.1.0"
authors = ["Martin Charles <martincharles07@gmail.com>"]

[dependencies]
rustfft = { git = "https://github.com/awelkie/RustFFT.git" }
base64 = "0.13"

[dev-dependencies]
approx = "0.5"
